namespace CobrancaBBApi.Model.Enum
{
    public enum EnumTipoTitulo
    {
        CHEQUE = 1,
        DUPLICATAMERCANTIL = 2,
        DUPLICATAMTILPORINDICACAO = 3,
        DUPLICATADESERVICO = 4,
        DUPLICATADESRVCINDICACAO = 5,
        DUPLICATARURAL = 6,
        LETRADECAMBIO = 7,
        NOTADECREDITOCOMERCIAL = 8,
        NOTADECREDITOAEXPORTACAO = 9,
        NOTADECREDITOINDULTRIAL = 10,
        NOTADECREDITORURAL = 11,
        NOTAPROMISSORIA = 12,
        NOTAPROMISSORIARURAL = 13,
        TRIPLICATAMERCANTIL = 14,
        TRIPLICATADESERVICO = 15,
        NOTADESEGURO = 16,
        RECIBO = 17,
        FATURA = 18,
        NOTADEDEBITO = 19,
        APOLICEDESEGURO = 20,
        MENSALIDADEESCOLAR = 21,
        PARCELADECONSORCIO = 22,
        DIVIDAATIVADAUNIAO = 23,
        DIVIDAATIVADEESTADO = 24,
        DIVIDAATIVADEMUNICIPIO = 25,
        CARTAODECREDITO = 31,
        BOLETOPROPOSTA = 32,
        BOLETOAPORTE = 33,
        OUTROS = 99
    }
}
