namespace CobrancaBBApi.Model.Enum
{
    public enum EnumTipoBaixaTitulo
    {
        NAOINFORMADO = 0,
        BAIXADOPORSOLICITACAO = 1,
        ENTREGAFRANCOPAGAMENTO = 2,
        COMANDADABANCO = 9,
        COMANDADACLIENTEARQUIVO = 10,
        COMANDADACLIENTEONLINE = 11,
        DECURSOPRAZOCLIENTE = 12,
        DECURSOPRAZOBANCO = 13,
        PROTESTADO = 15,
        LIQUIDADOANTERIORMENTE = 31,
        HABILITADOEMPROCESSO = 32,
        TRANSFERIDOPARAPERDAS = 35,
        REGISTRADOINDEVIDAMENTE = 51,
        BAIXAAUTOMATICA = 90
    }
}
