namespace CobrancaBBApi.Model.Enum
{
    public enum EnumOcorrenciaCartorio
    {
        TITULOPROTOCOLADOANTIGOTEC = 0,
        TITULOPAGOEMCARTORIO = 1,
        TITULOPROTESTADOANTIGODDP = 2,
        TITULORETIRADOCARTORIOANTDDS = 3,
        TITULOSUSTADOJUDICIALMENTE = 4,
        TITULORECUSADOSEMCUSTAS = 5,
        TITULORECUSADOCOMCUSTAS = 6,
        TITULOPAGOLIQUIDACAOCONDICIONAL = 7,
        TITULOACEITO = 8,
        CUSTASDEEDITAL = 9,
        LQCARTORIOAGSEMIAUTOM = 20,
        CHQDEVOLVTITENCPROT = 21,
        TITULOSUSTADODEFINITIVO = 22,
        RETIRADAAPOSSUSTACAOJUDICIAL = 23,
        PAGTOCONDICIONALVIASELTEC = 59,
        TITULOPAGOEMCARTORIOSELTEC = 60
    }
}
