namespace CobrancaBBApi.Model.Enum
{
    public enum EnumEstadoTituloCobranca
    {
        NORMAL = 1,
        MOVIMENTOCARTORIO = 2,
        EMCARTORIO = 3,
        TITULOCOMOCORRENCIADECARTORIO = 4,
        PROTESTADOELETRONICO = 5,
        LIQUIDADO = 6,
        BAIXADO = 7,
        TITULOCOMPENDENCIADECARTORIO = 8,
        TITULOPROTESTADOMANUAL = 9,
        TITULOBAIXADOPAGOEMCARTORIO = 10,
        TITULOLIQUIDADOPROTESTADO = 11,
        TITULOLIQUIDPGCRTO = 12,
        TITULOPROTESTADOAGUARDANDOBAIXA = 13,
        TITULOEMLIQUIDACAO = 14,
        TITULOAGENDADO = 15,
        TITULOCREDITADO = 16,
        PAGOEMCHEQUEAGUARDLIQUIDACAO = 17,
        PAGOPARCIALMENTECREDITADO = 18,
        EMPROCESSAMENTO = 80
    }
}
